name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint-prose:
    name: Lint prose
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: errata-ai/vale-action@reviewdog
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          files: ./pages
          fail_on_error: true
